

<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href="stylecadastro.css" rel="stylesheet" type="text/css">

    <link href="styleprincipal.css" rel="stylesheet" type="text/css">
    <title>Game Task</title>
  </head>
  <body>
    <div class="tudopr">
        
			<nav class="navbar fixed-top navbar-expand-lg navbar-light " style="background-color: #87D0FF;">
                <div class="container-fluid">
                   <a class="navbar-brand" href=""> <img src="LogoTCC.png" width="30" height="30" class="d-inline-block align-top" alt="">
                        Game Task </a>
                    
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
                        <span class="navbar-toggler-icon"></span></button>
                </div>   
            </nav>                  
      
			
			
			<div class="conteudocd"> <!-- O que foi selecionado na barra opções -->
                <div class="alterinfo">
                    <h3>Termos de Uso</h3>
                </div>
                <div class="cpalterinfos" style="padding-right:5%; padding-left:5%;">

Bem-vindo ao sistema GameTask. O sistema GameTask apresenta os Termos de Uso (“Termos de Uso”) de seu website (https:/gametask.com.br), sua plataforma e seus serviços (juntos, a “Plataforma”) estabelecidos neste documento. Nossa Política de Privacidade, também aplicável aos serviços, pode ser encontrada em https://gametask.com.br/politica-privacidade. <br><br>
Reservamo-nos o direito de alterar ou modificar estes Termos de Uso ao nosso exclusivo critério, a qualquer momento. Qualquer alteração ou modificação a estes Termos de Uso entrará em vigor imediatamente após a publicação em nosso website. Nós alertaremos sobre quaisquer mudanças nos Termos de Uso, onde o usuário tem a responsabilidade de mudar<br><br>
Os Termos de Uso e a Política de Privacidade são válidos para todos os usuários de nossa Plataforma. <br><br>
O uso continuado dos nossos serviços constitui a aceitação de quaisquer alterações ou modificações feitas nos Termos de Uso. <br><br>
1. Aceitação aos Termos de Uso<br><br>
1.1 Ao acessar e/ou usar os serviços do Sistema GameTask, informações inseridas, posts realizados, ranking do jogador, contatos realizados e demais serviços oferecidos em nosso website (“Serviços”), você concorda com os Termos de Uso, suas cláusulas e condições, conforme abaixo detalhadas. <br><br>
1.2. Você está autorizado a utilizar os Serviços do Sistema GameTask somente se você concorda com todas regras e condições estabelecidas nos Termos de Uso. <br><br>
1.3. Se você não concorda com estes Termos de Uso, você não está autorizado a acessar ou utilizar os Serviços oferecidos em nosso website. A utilização dos Serviços sistema GameTask está expressamente condicionada ao seu consentimento às regras dos Termos de Uso. <br><br>
2. Jogadores e Times: <br><br>
2.1 Jogadores: O uso das áreas públicas do Sistema GameTask está disponível para qualquer pessoa registrada como jogador ou time no site. Qualquer pessoa com pelo menos 13 anos de idade, residente em qualquer parte do mundo, pode se tornar usuário do Sistema GameTask. A palavra “Jogador” ou “Time” se referirá a qualquer pessoa que tenha se registrado em nosso website, sendo que a definição de time ou jogador é pré-definida pelo usuário, e a responsabilidade de se identificar corretamente como time ou jogador é unicamente do próprio usuário. <br><br>
2.3 Senha e Segurança. Quando você completar o seu processo de registro, você criará uma senha que habilitará seu acesso à nossa Plataforma. Você concorda em manter a confidencialidade da sua senha e é inteiramente responsável por qualquer dano resultante da não manutenção dessa confidencialidade e de todas as atividades que ocorrerem através do uso de sua senha. Você concorda em nos notificar imediatamente de qualquer acesso não autorizado de sua senha ou outra quebra de segurança. Você concorda que o Sistema GameTask não será responsabilizado por qualquer perda ou dano que ocorra a partir do não cumprimento desta cláusula. <br><br>
3. Informações Públicas e Privadas: <br><br>
3.1 “Suas Informações”: são definidas como qualquer informação postada por você ou que você nos dê (direta ou indiretamente), inclusive através do seu processo de registro ou do seu uso de nossa Plataforma, postagens realizadas, informações inseridas dentro de nossa plataforma, ou e-mail. Você é o único responsável por Suas Informações, e nós agimos como um canal passivo para a distribuição e publicação de suas Informações Públicas. <br><br>
3.2 “Informações Públicas”: seu nome, sua descrição, sua idade, sua localidade, bem como qualquer parte de Suas Informações que, através do uso de nossa Plataforma ou de outra maneira, você envie ou disponibilize para a inclusão em áreas públicas de nosso website. <br><br>
3.3 “Informação Privada”: qualquer outra parte de Suas Informações que não sejam Informações Públicas será referida como Informação Privada. <br><br>
3.4 “Áreas públicas”: são aquelas áreas do nosso website que são acessíveis para alguns ou todos os jogadores cadastrados (p.ex., não restritas à sua visualização apenas) ou para o público geral. <br><br>
3.5 Acessibilidade das Informações Públicas. As suas Informações Públicas podem ser acessíveis e publicadas por programas de publicação automática e por ferramentas de busca. <br><br>
3.6 Restrições. Ao considerar o uso de nossa Plataforma, você concorda que as Suas Informações: (a) não devem ser fraudulentas; (b) não devem infringir nenhum direito autoral de terceiros, patente, marca registrada, direito de distribuição ou outro direito de propriedade intelectual, de publicação ou privacidade; (c) não devem violar nenhuma lei, estatuto, ordenação ou regulamento; (d) não devem ser difamatórias, caluniosas, ameaçadoras ou abusivas; (e) não devem ser obscenas ou conter pornografia, pornografia infantil, ou fotos de pessoas despidas; (f) não devem conter vírus, cavalos de troia, worms, time bombs, cancelbots, easter eggs ou outras rotinas de programação que possam danificar, interferir, interceptar ou desapropriar qualquer sistema, dado ou informação pessoal; (g) não devem nos responsabilizar ou fazer com que percamos (total ou parcialmente) o serviço do nosso Provedor de Internet ou outros fornecedores; (h) não devem criar links direta ou indiretamente a qualquer material que você não tenha direito de incluir ou linkar. <br><br>
3.7 Obrigações: Você concorda também que deverá nos informar um endereço válido de e-mail, tanto na hora de seu registro conosco quanto a cada vez que o seu e-mail mudar. Você concorda também que o seu perfil de Jogador ou de Time, a GameTask, postagens de comentários em blogs, uploads de fotos ou quaisquer porções do website reservadas apenas a uso dos Jogadores ou times não devem ser usadas por você para atividades comerciais, vendas de bens e serviços, ou a promoção de uma companhia, bem ou serviço não relacionado ao tópico ou espírito da GameTask em particular. Você será exclusivamente responsável pelas informações que você postar nas áreas publicamente acessíveis da Plataforma, independentemente de sua intenção ou não de fazê-lo. <br><br>
3.8 Privacidade: Todas as informações pessoais relacionadas ao uso dos Serviços ou ao uso do website GameTask estão sujeitas à nossa Política de Privacidade que pode ser encontrada em https://gametask.com.br/politica-privacidade. <br><br>
3.9 Licença. Nós não clamamos propriedade de Suas Informações. Nós usaremos as suas Informações Pessoais Identificáveis apenas de acordo com a nossa Política de Privacidade. Entretanto, para nos autorizar a usar suas Informações Públicas e para nos assegurar de que não violamos nenhum direito que você possa ter sobre suas Informações Públicas, você garante a GameTask o direito não-exclusivo, universal, sem pagamento de royalties, em caráter total, definitivo, irrevogável e irretratável, de utilizar, a qualquer tempo, no Brasil e/ou no exterior e de exercer, comercializar e explorar todos os direitos de cópia, publicidade, e direitos de base de dados que você possua sobre suas Informações Públicas, através de qualquer meio conhecido ou que venha a ser criado futuramente, e para qualquer fim. <br><br>
3.10 Restrições no Nosso Uso de Suas Informações. Exceto se especificado contrariamente em nossa Política de Privacidade, nós não venderemos, alugaremos ou divulgaremos nenhuma parte de suas Informações Pessoais Identificáveis (como definidas em nossa Política de Privacidade) sobre você (incluindo seu endereço de e-mail) para terceiros. <br><br>
3.11 Consentimento de Divulgação. Você entende e concorda que a GameTask pode divulgar Suas Informações se requerida a fazê-lo por lei ou por acreditar de boa-fé que essa divulgação é razoável e necessária para: (a) cooperar com um procedimento judicial, uma ordem judicial ou processo legal sobre nós ou nosso website; (b) reforçar os Termos de Uso; (c) replicar a respeito da infração do direito de terceiros por Suas Informações; (d) proteger os direitos, propriedades ou a segurança pessoal da GameTask, seus empregados, usuários e público. <br><br>
3.12 Consentimento de divulgação: A GameTask reserva-se o direito, a seu exclusivo critério, de suspender ou terminar o seu uso de nossa Plataforma e de nossos Serviços, de recusar todo e qualquer uso corrente ou futuro de todas ou algumas partes de nossa Plataforma e/ou Serviços. <br><br>
4. Condições gerais de uso dos Serviços<br><br>
4.1. Ao aceitar estes Termos de Uso, você tem o direito não exclusivo, intransferível, não sub-licenciável e limitado de entrar, acessar e usar os Serviços, unicamente para uso pessoal e não comercial. <br><br>
4.2 Todos os direitos não previstos expressamente nestes Termos de Uso estão reservados a GameTask<br><br>
4.3. Você concorda que os Serviços são para o seu uso pessoal e não comercial e que ninguém além de você usará os Serviços. Você não tem direitos de cópia ou reprodução no todo ou em parte, de qualquer parte dos Serviços de propriedade da GameTask<br><br>
4.4 Além da licença limitada de uso estabelecida nestes Termos de Uso, você não tem qualquer outro direito, título ou propriedade sobre os Serviços. Você entende e reconhece que, em quaisquer circunstâncias, os seus direitos com relação ao Serviços serão limitados pelos direitos autorais e/ou leis de propriedade intelectual aplicáveis e ainda por estes Termos de Uso. <br><br>
4.5 A GameTask poderá modificar os Serviços e/ou Conteúdo ou descontinuar a sua disponibilidade a qualquer momento. <br><br>
4.6 Você é o único responsável pela obtenção, pagamento e manutenção de todos os serviços de telefonia, acesso à internet, plano de dados, tarifas e/ou outras taxas, mensalidades e custos associados ao seu acesso e uso dos Serviços, bem como pelo software, hardware de computador e outros equipamentos necessários para o uso e acesso aos Serviços. <br><br>
4.7. Não obstante outras disposições contidas nestes Termos de Uso, os Serviços estão disponíveis para seu uso por um período que começa a partir do registro de seus dados junto com o pagamento correspondente ao plano escolhido, incluindo as suas renovações. <br><br>
4.8. Você não deve tentar nem apoiar as tentativas de terceiros para driblar, reverter a engenharia, decodificar, decompilar, desmontar ou fraudar ou interferir de qualquer forma com aspectos dos Serviços. Você não deve distribuir, intercambiar, modificar, vender ou revender ou retransmitir a qualquer pessoa qualquer parte dos Serviços, incluindo, mas não se limitando, a qualquer texto, imagem ou áudio, para qualquer finalidade empresarial comercial ou pública. Você concorda em não copiar, vender, distribuir ou transferir o Conteúdo e/ou Serviços GameTask<br><br>
5. Uso da Plataforma<br><br>
5.1 Responsabilidade e Controle. Você, e não a GameTask, é inteiramente responsável por Suas Informações que faça upload, poste, distribua, envie por e-mail ou de alguma outra forma torne disponível via nossa Plataforma. Nós não controlamos suas Informações Públicas ou as Informações Públicas de outros Jogadores e Times ou postadas por eles, e não garantimos a precisão, integridade ou a qualidade de Suas Informações ou das Informações postadas por ou sobre outros Jogadores e Times, nem endossamos nenhuma opinião expressada por você ou por outros Jogadores e Times. Você entende que usando nossa Plataforma, você pode ser exposto a informações ofensivas, indecentes ou com as quais não concorde. Nós não temos nenhuma obrigação de monitorar, nem tomamos qualquer responsabilidade pelas Suas Informações, pelas Informações Públicas ou informações a respeito de quaisquer assuntos ou postadas por outros Usuários. Você concorda que sob nenhuma circunstância a GameTask, seus diretores, sócios ou funcionários poderão ser responsabilizados por quaisquer informações, incluindo, mas não se limitando a erros ou omissões nas Suas Informações ou nas Informações Públicas postadas por ou sobre outros Jogadores e Times, por perdas e danos de qualquer tipo, ocorridas como resultado do uso das Suas Informações ou de quaisquer Informações Públicas de ou sobre outros Jogadores e Times que venham a ser postadas, enviadas por e-mail, transmitidas ou disponibilizadas de qualquer outra maneira conectada à nossa Plataforma, ou por qualquer falha em corrigir ou remover quaisquer dessas informações. <br><br>
5.2 Condições para Suspensão ou Término dos Serviços. <br><br>
5.2.1 Os seguintes tipos de ação são vedados no website e na Plataforma GameTask e são passíveis de suspensão e/ou término imediato do seu status de Jogador ou Time: <br><br>
(a) Uso de nossa Plataforma para: (i) ameaçar ou intimidar outra pessoa de qualquer forma, incluindo a restrição ou inibição do uso de nossa Plataforma; (ii) personificar qualquer pessoa (incluindo a equipe da GameTask ou outros usuários), ou atestar falsamente afiliação ou representação de qualquer pessoa ou companhia, através do uso de endereços de e-mail similares, apelidos, ou a criação de contas falsas ou qualquer outro método ou procedimento; (iii) disfarçar a origem de quaisquer Informações Públicas que sejam transmitidas a terceiros; (iv) perseguir ou perturbar outrem; (v) coletar ou armazenar dados pessoais de outros usuários; <br><br>
(b) Postar quaisquer Informações Públicas ou outro material: (i) que seja ilegal, ofensivo, racista, preconceituoso, ameaçador, abusivo, perturbador, difamatório, intimidador, vulgar, obsceno, profano, acusatório, que invada a privacidade de outrem (inclusive a postagem de e-mails privados ou informações de contato de outros usuários), odioso, racial, eticamente ou de qualquer outra forma contestável, incluindo quaisquer Informações Públicas ou outro material que possa ser considerado um discurso de ódio; (ii) que seja obsceno, pornográfico ou adulto por natureza; (iii) que você não tenha o direito de disponibilizar por qualquer lei ou por contrato; (iv) que infrinja qualquer patente, marca registrada, segredo comercial, direitos autorais ou quaisquer outros direitos de propriedade intelectual ou direitos de terceiros; (v) que seja qualquer tipo de propaganda ou material promocional não solicitado, ou qualquer outra forma de solicitação (incluindo, mas não se limitando a “spam”, “junk mail”, e correntes de e-mail); ou (vi) que seja de qualquer outra forma inapropriado ou postado de má fé; <br><br>
(c) Encorajar outrem a violar os Termos de Uso ou se recusar a seguir instruções da equipe da GameTask<br><br>
(e) Violar (intencional ou não intencionalmente) os Termos de Uso, ou de qualquer lei, ordenação, estatuto ou regulamento local, estadual, nacional ou internacional aplicável. <br><br>
5.2.2 Mesmo que nós proibamos o conteúdo e as condutas acima, você entende e concorda que você poderá vir a ser exposto a tais condutas e conteúdos e que usa a Plataforma a seu próprio risco. Para os propósitos destes Termos de Uso, “postar” inclui o upload, a postagem, distribuição, envio de e-mails, publicação, transmissão ou disponibilização de alguma outra forma. <br><br>
5.2.3 Sem se limitar aos ao disposto acima, a GameTask o direito de remover quaisquer Informações Públicas ou outro material que viole esses Termos de Uso ou seja de outra maneira questionável. <br><br>
5.3 Não-Interferência com a Plataforma. Você concorda que não irá: (a) fazer upload, postar, publicar, distribuir, enviar por e-mail ou transmitir de qualquer outra forma rotinas de programação, arquivos ou programas com a intenção de interromper, destruir ou limitar as funcionalidades de qualquer software ou hardware ou equipamento de telecomunicação; (b) interferir com ou perturbar nossa Plataforma ou com as redes conectadas ao nosso website através do uso de nossa Plataforma, ou desobedecer quaisquer requerimentos, procedimentos, políticas ou regulamentos das redes conectadas ao nosso website, ou de alguma outra maneira interferir com a nossa Plataforma em qualquer sentido, incluindo através do uso de JavaScript, ou outros códigos; (c) agir de qualquer maneira que imponha uma carga excessivamente pesada, que seja desproporcional ou não razoável, em nossa infraestrutura; (d) copiar, reproduzir, alterar, modificar ou exibir publicamente qualquer informação que esteja disponível em nosso website (exceto as Suas Informações), ou criar trabalhos derivados do nosso website (exceto Suas Informações), com o entendimento de que tais ações constituiriam infração de direitos autorais ou outro tipo de violação à propriedade intelectual e/ou industrial da GameTask ou de quaisquer terceiros, exceto se autorizado por escrito e com antecedência pela GameTask ou pelo terceiro. <br><br>
5.4 Práticas Gerais de Uso da Plataforma. Você declara saber e entender que nós podemos estabelecer práticas e limites gerais no que diz respeito ao uso de nossa Plataforma. Você concorda que nós não nos responsabilizamos nem podemos ser responsabilizados pelo armazenamento ou apagamento, ou pela falha em armazenar ou apagar, qualquer uma de Suas Informações. Você entende que nós nos reservamos o direito de suspender Jogadores e Times que estejam inativos por um período extenso de tempo. Você entende que nós nos reservamos o direito de mudar essas práticas e limites gerais a qualquer momento, a nosso critério, com ou sem aviso.
6. Comunicados da Equipe GameTask
6.1 Você entende e concorda que nós podemos enviar certos comunicados, como anúncios de serviços da GameTask, bem como ofertas de bens e serviços relevantes e que beneficiem você ou qualquer grupo de Jogadores ou Times unidos por afinidade que você possa vir a participar, e que esses comunicados são considerados parte de nossa Plataforma. <br><br>
7. Links
7.1 Nós podemos providenciar, ou terceiros podem providenciar e publicar, links para outros websites ou recursos. Por não termos controle sobre tais websites ou recursos, você entende e concorda que nós não somos responsáveis pela disponibilidade de tais websites e recursos, e nós não endossamos e não nos responsabilizamos nem somos passíveis de ser responsabilizados por qualquer conteúdo, publicidade, produto, ou outro material disponível neste ou através deste website ou recurso. <br><br>
7.2 Você também entende e concorda que a GameTask não será responsável nem poderá ser responsabilizada, direta ou indiretamente, por quaisquer perdas e danos causadas ou alegadas de terem sido causadas ou relacionadas ao uso de qualquer conteúdo, bem ou serviço disponível na Plataforma ou através do uso de qualquer um desses websites, recursos e/ou serviços. <br><br>
8. Garantias e Responsabilidades
8.1 Isenção de Garantias. Você usa a nossa Plataforma a seu próprio e exclusivo risco. Nossa Plataforma é oferecida a você “como é” e “como está disponível”. Nós nos isentamos de garantias e condições de qualquer tipo, sejam expressas, implícitas ou instituídas, incluindo mas não se limitando a garantias relacionadas à segurança, confiabilidade, conveniência e performance de nossa Plataforma. Nós nos isentamos ainda de quaisquer garantias sobre informações ou conselhos obtidos através de nossa Plataforma. Isentamo-nos de quaisquer garantias de terceiros por serviços ou bens recebidos através ou anunciados em nossa Plataforma ou recebidos através de links exibidos em nossa Plataforma, bem como por qualquer informação ou conselho recebido através de quaisquer links exibidos em nossa Plataforma. Além disso, nenhum conselho ou informação, seja oral ou escrita, obtida de você por nós, deve criar nenhum tipo de garantia. <br><br>
8.2 Suposição de Risco. Você entende e concorda que ao fazer download ou obter qualquer outra forma de acesso ao nosso material ou dados através do uso de nossa Plataforma ao seu próprio critério e risco e que você será o único responsável por quaisquer danos ao seu computador ou perda de dados que resulte do download deste material ou dados. <br><br>
8.3 Limitação de Responsabilidade. Você concorda que, em nenhuma circunstância, a GameTask poderá ser responsabilizada por qualquer dano direto, indireto, incidental, especial, consequencial ou punitivo, incluindo mas não se limitando a perdas e danos, lucros cessantes, perda de uma chance, outras perdas e danos intangíveis (ainda que a GameTask tenha sido alertada sobre a possibilidade de ocorrência de tais danos), relacionado ao uso dos Serviços ou de nossa Plataforma, nem com relação à incapacidade e/ou impossibilidade de usá-los (incluindo hipóteses de negligência). <br><br>
9. Indenização<br><br>
9.1 Você concorda em defender, indenizar e proteger a GameTask, seus diretores, sócios, agentes, funcionários, consultores, afiliados, subsidiários e parceiros contra toda e qualquer reclamação, perda, dano, responsabilização, julgamento, avaliação, multa, custo e outras despesas, incluindo honorários advocatícios, resultantes ou relacionados ao uso feito por você dos Serviços ou de qualquer violação dos Termos de Uso, uso da Plataforma, Suas Informações, violação de qualquer lei, estatuto, ordem ou regulamento ou direitos de terceiros e concorda em reembolsar a GameTask por quaisquer perdas, custos e despesas em que ela incorra por consequência disso. <br><br>
10. Rescisão<br><br>
10.1 Você concorda que nós, ao nosso critério, podemos disparar um alerta, suspender temporariamente, indefinidamente ou remover completamente qualquer conteúdo ou informação postada por você, ou encerrar com o seu status de Jogador ou Time com a sua capacidade de uso total ou parcial de nossa Plataforma, por qualquer razão, incluindo mas não se limitando a (a) por falta de uso; (b) se nós acreditarmos que você violou ou agiu de forma inconsistente com o espírito destes Termos de Uso ou dos documentos incorporados como referência; (c) se não formos capazes de verificar ou autenticar qualquer informação que você nos forneça; (d) se acreditarmos que suas ações possam gerar responsabilidade civil a você, aos nossos usuários ou a nós. <br><br>
10.2 Você declara-se ciente de que o encerramento da sua conta ou do acesso total ou parcial à Plataforma por motivo esclarecido nesses Termos de Uso poderá ser efetuado sem aviso prévio, e entende e concorda que poderemos imediatamente desativar ou apagar a sua conta e todas as informações e arquivos relativos a ela e/ou barrar seu acesso futuro à nossa Plataforma. Você também concorda que nós não podemos ser responsabilizados por você ou por terceiros pelo encerramento do seu uso de todas ou quaisquer partes da Plataforma. <br><br>
11. Propriedade Intelectual
11.1 Direitos autorais. O conteúdo publicado no website GameTask e outros trabalhos de autoria encontrados na Plataforma como parte dos Serviço ("Conteúdo") estão protegidos pelas leis e tratados de direitos autorais nacionais e internacionais, assim como outras leis e tratados de propriedade intelectual. O Conteúdo é licenciado, não vendido. Você não pode fazer cópias não autorizadas ou usar nenhum Conteúdo, exceto como especificado aqui e de acordo com as leis aplicáveis. Todos os direitos autorais do Conteúdo e dos Serviços (incluindo, mas não se limitando a imagens, fotografias, animações, vídeos, áudio, música, texto, layout incorporados nos Serviços) são de propriedade da GameTask. Você concorda em cumprir com todas as leis de proteção dos direitos autorais relacionadas ao uso dos Serviços e do Conteúdo. A GameTask reserva-se o direito de tomar as medidas que julgar apropriadas, a seu exclusivo critério, a fim de proteger os direitos autorais do Conteúdo e dos Serviços, além das condições previstas nestes Termos de Uso. <br><br>
11.3 Não é permitido aos Usuários tentar reconfigurar, desmontar ou fazer engenharia reversa no website, nos Serviços e/ou no Conteúdo da GameTask<br><br>
11.4 Marcas. Você não está autorizado a utilizar nenhum marca e/ou sinais distintivos encontrados no website, no Conteúdo e/ou nos Serviços da GameTask. Você não pode copiar, exibir ou usar nenhuma das marcas comerciais sem consentimento prévio por escrito do seu proprietário. Qualquer uso não autorizado poderá violar as leis de propriedade industrial, leis de privacidade, de propriedade intelectual e ainda estatutos civis e/ou criminais. <br><br>
11.5 Todos os direitos e licenças não concedidos expressamente nestes Termos de Uso são reservados aos proprietários dos Conteúdos e/ou Serviços. Estes Termos de Uso não concedem quaisquer licenças implícitas. <br><br>
12. Proibição de Revenda<br><br>
12.1 Você concorda em não reproduzir, duplicar, copiar, vender, revender ou explorar com quaisquer fins comerciais, qualquer porção da Plataforma GameTask, nem fazer uso da Plataforma ou do acesso esta para o fim de vendas de bens ou serviços, ou a promoção de uma companhia, bem ou serviço. <br><br>
13. Disposições Gerais<br><br>
13.1. Estes Termos de Uso, juntamente com a Política de Privacidade publicada no nosso website, constituem o acordo integral entre as Partes com relação ao objeto em questão, e substituem todos os acordos anteriores, escritos ou verbais. <br><br>
13.2. As Partes são contratantes independentes, não resultando este instrumento na criação de qualquer sociedade, franquia, representação de vendas ou relações que não as expressamente previstas nestes Termos de Uso. <br><br>
13.3. Caso qualquer uma das cláusulas e condições destes Termos de Uso venha a ser declarada nula, no todo ou em parte, por qualquer motivo legal ou contratual, as demais cláusulas continuarão em pleno vigor e efeito. <br><br>
13.4 A tolerância ou o não exercício, por qualquer das Partes, de quaisquer direitos a ela assegurados nestes Termos de Uso ou na lei em geral não importará em novação ou em renúncia a qualquer desses direitos, podendo a referida Parte exercê-los durante a vigência destes Termos de Uso. <br><br>
13.4 Notificações, avisos ou comunicações relativas aos presentes Termos de Uso serão enviados por escrito, por meio de carta protocolada ou com aviso de recebimento, fac-símile ou correspondência eletrônica com comprovação de recebimento, por qualquer uma das Partes à outra. <br><br>

                </div>
                 <div class="alterinfo">
                    <h3>Política de Privacidade</h3>
                </div>
                <div class="cpalterinfos" style=" margin-top: 1%; padding-right:5%; padding-left:5%;">

Este é o website gametask.com.br<br><br>
A GameTask respeita o direito à privacidade e zela pela segurança dos dados pessoais de seus usuários. <br><br>
A nossa Política de Privacidade esclarece como coletamos e utilizamos as informações para que nossos visitantes sintam-se seguros ao navegar e utilizar o nosso website. <br><br>
A fim de proporcionar maior segurança e transparência, poderemos alterar periodicamente a Política de Privacidade. Por favor confira-a periodicamente, e especialmente antes de você fornecer qualquer dado pessoal. <br><br>
Ao utilizar este website, você concorda com os termos da presente Política de Privacidade. <br><br>
1. Informações coletadas: <br><br>
Nosso servidor não coleta automaticamente nenhuma informação sobre o domínio ou endereço de e-mail de nossos visitantes. <br><br>
Coletamos apenas mediante prévia solicitação, o domínio e endereço de e-mail dos visitantes de nossa página, os endereços de e-mail daqueles que se comunicam conosco através dele, os endereços de e-mail dos que se comunicam conosco através do nosso Chat ao vivo. Além disso, agregamos informações sobre quais páginas os consumidores acessam ou visitam, informações fornecidas voluntariamente pelos usuários, como as coletadas em pesquisas e no momento de registro no site, como nome e endereço, número de telefone, etc. <br><br>
Ao fornecer informações através deste site, você consente com a coleta, uso e divulgação de informações, de acordo com esta Política de Privacidade. <br><br>
2. Uso das informações coletadas: <br><br>
As informações que coletamos são usadas com o objetivo de melhorar o conteúdo de nosso website, notificar os usuários sobre as atualizações disponíveis entre outros improva mentos<br><br>
Com objetivos de estatística e finalidades comerciais, informações gerais dos usuários, sem identificação, tais como dados geográficos, demográficos e de perfil de consumo poderão ser divulgados a parceiros, patrocinadores, anunciantes ou a outras organizações, sem que sejam revelados nomes ou outros dados pessoais. <br><br>
A GameTask não disponibiliza e-mails e demais informações pessoais de usuários cadastrados a outras organizações e/ou parceiros, salvo quando expressamente autorizado ou em circunstâncias previstas nesta Política. <br><br>
As pessoas que nos fornecerem seus números de telefone poderão ser contatados pela GameTask via telefone, com informações a respeito de novos produtos e serviços ou eventos próximos. Se você não deseja receber essas ligações, por favor nos avise enviando um e-mail para o endereço gameworktcc@gmail.com<br><br>
3. Links para outros sites: <br><br>
Este website poderá conter links para outros sites externos, parceiros e/ou patrocinadores, que podem ter políticas de privacidade diferentes das nossas, estando assim sujeitas às suas próprias práticas de obtenção e uso de dados. Lembre-se que se você fornecer informações pessoais em outros sites, fóruns ou chats, tais informações poderão ser recolhidas e utilizadas indevidamente por terceiros. <br><br>
A GameTask não se responsabiliza pelo conteúdo de tais sites nem pelo manuseio das informações por terceiros. Por isso, recomendamos que nossos usuários sempre leiam as normas de relacionamento e política de privacidade específicas dentro do próprio site do parceiro ou patrocinador que colete suas informações. <br><br>
A Política de Privacidade da GameTask se aplica unicamente às informações coletadas pela GameTask através do site https://gametask.com.br. <br><br>
4. Crianças:
Este site não se destina a menores de 13 anos de idade. A Escola do Marketing Digital não coleta ou solicita dados pessoalmente identificáveis de visitantes dessa faixa etária intencionalmente, exceto quando permitido pela respectiva legislação. Qualquer pessoa que nos preste suas informações pessoais através da GameTask declara que tem 13 anos de idade ou mais. <br><br>
Caso seu filho tenha enviado dados pessoais e você queira excluir tais dados dos nossos registros, poderá fazê-lo através de solicitação para o e-mail gameworktcc@gmail.com<br><br>
5. Segurança:
A GameTask utiliza medidas de segurança comercialmente razoáveis para proteger as informações contidas em nossos servidores e banco de dados. Contudo, sabe-se que nenhum sistema de segurança é 100% seguro. Deste modo, ainda que a GameTask sempre faça o possível para proteger suas informações pessoais, não temos como garantir a absoluta segurança dos nossos servidores. É possível ainda que os dados fornecidos por você sejam interceptados por terceiros durante a transmissão. É uma decisão pessoal a utilização do serviço nessas condições. <br><br>
Quando recebemos e transferimos certos tipos de informação confidencial, como dados pessoas e afins, redirecionamos os visitantes a servidores seguros notificando-os através de uma janela pop-up em nosso website. Sua senha é secreta, mantenha-a em segurança e procure não divulgá-la a ninguém. <br><br>
Caso você esqueça a sua senha, uma nova será fornecida, mediante solicitação prévia, e enviada para a sua conta de e-mail informada. Sugerimos que você escolha uma senha não óbvia, misturando letras e números. Lembre-se que você é responsável por manter o sigilo de suas senhas e qualquer informação da sua conta da GameTask<br><br>
Não solicitaremos, em nenhuma hipótese, seja por e-mail ou telefone, sua senha pessoal. <br><br>
Recomendamos que você se desconecte de sua conta da GameTask e feche a janela do seu navegador quando concluir sua navegação na Internet. Este procedimento evita que terceiros tenham acesso aos seus dados pessoais, caso você compartilhe um computador com alguém ou esteja usando um computador em local público. <br><br>
6. Como atualizar, corrigir ou excluir suas informações: <br><br>
Você é responsável por manter suas informações de registro completas e atualizadas. Para atualizar as suas informações de registro, acesse a sua conta da GameTask e faça a alteração desejada para alterar as suas preferências de usuário. <br><br>
7. Disposições gerais: <br><br>
Ao utilizar nosso website, você manifesta sua concordância com esta Política de Privacidade, que poderá ser alterada periodicamente. Se você não concordar com esta Política de Privacidade, não utilize o nosso website nem os serviços nele oferecidos. <br><br>
A GameTask reserva-se o direito de alterar esta Política de Privacidade, o que será avisado aos nossos usuários por meios razoáveis, inclusive através de e-mail para o endereço informado e/ou publicando a notificação e a política alterada no site GameTask<br><br>
A continuação do uso dos nossos serviços e do website após as alterações da Política de Privacidade significa que você aceita e concorda com as mudanças realizadas. As informações coletadas ou fornecidas depois da atualização da Política de Privacidade será regida por esta última. <br><br>
8. Entre em contato: <br><br>
Seus comentários são bem vindos. Caso você tenha dúvidas ou reclamações sobre a nossa Política de Privacidade, entre em contato pelo e-mail gameworktcc@gmail.com<br><br>
Se você entender que nosso website não está seguindo a política informada, por favor entre em contato através do e-mail informado acima. <br><br>


                </div>
				
			
            </div>
      </div>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>
</html>